version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Freqtrade_order
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 main.py